# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
node_js:
  - "9"
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- git init
- git config user.name "charlesmaxwellyoung"
- git config user.email "charlesmaxwellyoung@gmail.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
  - hexo clean
  - hexo generate
after_script:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://$access_token@github.com/CharlesMaxwellYoung/blog_hexo.git gh-pages
